require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AddGroupToUsersController do

  # This should return the minimal set of attributes required to create a valid
  # AddGroupToUser. As you add validations to AddGroupToUser, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "group" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AddGroupToUsersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all add_group_to_users as @add_group_to_users" do
      add_group_to_user = AddGroupToUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:add_group_to_users).should eq([add_group_to_user])
    end
  end

  describe "GET show" do
    it "assigns the requested add_group_to_user as @add_group_to_user" do
      add_group_to_user = AddGroupToUser.create! valid_attributes
      get :show, {:id => add_group_to_user.to_param}, valid_session
      assigns(:add_group_to_user).should eq(add_group_to_user)
    end
  end

  describe "GET new" do
    it "assigns a new add_group_to_user as @add_group_to_user" do
      get :new, {}, valid_session
      assigns(:add_group_to_user).should be_a_new(AddGroupToUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested add_group_to_user as @add_group_to_user" do
      add_group_to_user = AddGroupToUser.create! valid_attributes
      get :edit, {:id => add_group_to_user.to_param}, valid_session
      assigns(:add_group_to_user).should eq(add_group_to_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AddGroupToUser" do
        expect {
          post :create, {:add_group_to_user => valid_attributes}, valid_session
        }.to change(AddGroupToUser, :count).by(1)
      end

      it "assigns a newly created add_group_to_user as @add_group_to_user" do
        post :create, {:add_group_to_user => valid_attributes}, valid_session
        assigns(:add_group_to_user).should be_a(AddGroupToUser)
        assigns(:add_group_to_user).should be_persisted
      end

      it "redirects to the created add_group_to_user" do
        post :create, {:add_group_to_user => valid_attributes}, valid_session
        response.should redirect_to(AddGroupToUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved add_group_to_user as @add_group_to_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        AddGroupToUser.any_instance.stub(:save).and_return(false)
        post :create, {:add_group_to_user => { "group" => "invalid value" }}, valid_session
        assigns(:add_group_to_user).should be_a_new(AddGroupToUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AddGroupToUser.any_instance.stub(:save).and_return(false)
        post :create, {:add_group_to_user => { "group" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested add_group_to_user" do
        add_group_to_user = AddGroupToUser.create! valid_attributes
        # Assuming there are no other add_group_to_users in the database, this
        # specifies that the AddGroupToUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AddGroupToUser.any_instance.should_receive(:update_attributes).with({ "group" => "" })
        put :update, {:id => add_group_to_user.to_param, :add_group_to_user => { "group" => "" }}, valid_session
      end

      it "assigns the requested add_group_to_user as @add_group_to_user" do
        add_group_to_user = AddGroupToUser.create! valid_attributes
        put :update, {:id => add_group_to_user.to_param, :add_group_to_user => valid_attributes}, valid_session
        assigns(:add_group_to_user).should eq(add_group_to_user)
      end

      it "redirects to the add_group_to_user" do
        add_group_to_user = AddGroupToUser.create! valid_attributes
        put :update, {:id => add_group_to_user.to_param, :add_group_to_user => valid_attributes}, valid_session
        response.should redirect_to(add_group_to_user)
      end
    end

    describe "with invalid params" do
      it "assigns the add_group_to_user as @add_group_to_user" do
        add_group_to_user = AddGroupToUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AddGroupToUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => add_group_to_user.to_param, :add_group_to_user => { "group" => "invalid value" }}, valid_session
        assigns(:add_group_to_user).should eq(add_group_to_user)
      end

      it "re-renders the 'edit' template" do
        add_group_to_user = AddGroupToUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AddGroupToUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => add_group_to_user.to_param, :add_group_to_user => { "group" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested add_group_to_user" do
      add_group_to_user = AddGroupToUser.create! valid_attributes
      expect {
        delete :destroy, {:id => add_group_to_user.to_param}, valid_session
      }.to change(AddGroupToUser, :count).by(-1)
    end

    it "redirects to the add_group_to_users list" do
      add_group_to_user = AddGroupToUser.create! valid_attributes
      delete :destroy, {:id => add_group_to_user.to_param}, valid_session
      response.should redirect_to(add_group_to_users_url)
    end
  end

end
